- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB Server
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Replace a localhost entry with our own
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: true
