- name: Building Frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing Nginx Server
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Removing the old Content Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Downloading and Unzipping the frontend Content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /root/roboshop-shell/roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Restarting the Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes


#echo -e '\e[33mInstalling Nignx\e[0m'
#yum install nginx -y &>>/tmp/roboshop.log
#
#echo -e '\e[33mRemoving the old Content\e[0m'
#rm -rf /usr/share/nginx/html/* &>>/tmp/roboshop.log
#
#echo -e '\e[33mDownloading the frontend Content\e[0m'
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>/tmp/roboshop.log
#
#echo -e '\e[33mUnziping the frontend content\e[0m'
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip &>>/tmp/roboshop.log
#
#cp /root/roboshop-shell/roboshop.conf /etc/nginx/default.d/roboshop.conf &>>/tmp/roboshop.log
#
#echo -e '\e[33mRestarting the Nginx\e[0m'
#systemctl enable nginx
#systemctl restart nginx &>>/tmp/roboshop.log