
- name: Install package with multiple repos disabled
  ansible.builtin.shell: yum module disable mysql -y

- name: Copy Repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

