
- name: Installing Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: PreSetup App
  ansible.builtin.import_tasks:
    file: preapp_setup.yml

- name: Downloading Maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: Mysql Setup
  ansible.builtin.import_tasks:
    file: mysql_schema_setup.yml

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
