- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Downloading and Unzipping the app Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Downloading and Unzipping the app Content from nexus
  ansible.builtin.unarchive:
    src: http://54.81.209.228:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes